server:
  port: 8082
spring:
  application:
    name: upload-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:    #缩略图
    width: 60
    height: 60
  tracker-list:    # tracker地址
    - 120.55.165.50:22122
logging:
  level:
    com:
      taiheblog: debug
th:
  upload:
    baseUrl: http://image.taiheblog.com/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp
      - image/jpg