server:
  port: 10010
spring:
  application:
    name: gateway-service
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
