server:
  port: 8001
spring:
  application:
    name: user-service
  datasource:
    username: root
    password: usr041500
    url: jdbc:mysql://localhost:3306/th_picture_share?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&characterEncoding=utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
